[package]
name = "rusty-patio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.26"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tokio = "1.26.0"
tokio-tungstenite = "0.18.0"
tungstenite = "0.18.0"
